# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0002_auto_20170425_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='descrip',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='destination',
            name='user_id',
        ),
        migrations.AddField(
            model_name='destination',
            name='user_id',
            field=models.ManyToManyField(related_name='joined', to='belt_exam_app.User'),
        ),
    ]
