# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0003_auto_20170425_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='belt_exam_app.User'),
        ),
    ]
