# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0004_auto_20170425_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
